import {describe,it,expect} from 'vitest';
import {createDesign,installRule,createMatch,commitComputer,advanceMatch,resolveAttempt,legalActions,compileDesign,setAbility,makeObservation,projectPublicView,type MatchState,type RuleId,type Action} from '../../src/core';
import {ALL_CHOICES} from '../../src/content';
import {cardDefinition,CARD_LIBRARY} from '../../src/cards/catalog';
import {craftCard,drawCards,mulliganCard,projectCounts,recipes} from '../../src/cards/engine';
const start=(...rules:RuleId[])=>createMatch(rules.reduce(installRule,createDesign()),12);
function play(m:MatchState,p:string,q='scissors',ability=false){const choose=(side:'player'|'computer',name:string):Action=>{const card=m.fighters[side].cardZone?.hand.find(c=>c.definition===name);return {kind:card?cardDefinition(card.definition).kind:name as Action['kind'],cardId:card?.uid,boost:0,ability:side==='player'&&ability};};return resolveAttempt({...m,phase:'awaitingPlayer',preparationComplete:true,computerCommitment:choose('computer',q)},choose('player',p),`turn-${m.attempt}`);}
function give(m:MatchState,side:'player'|'computer',...names:string[]){const z=m.fighters[side].cardZone!;z.hand=names.map(definition=>({uid:`test-${++z.serial}`,definition}));projectCounts(m.fighters[side]);}
const total=(m:MatchState,s:'player'|'computer'='player')=>{const z=m.fighters[s].cardZone!;return z.hand.length+z.draw.length+z.discard.length;};
describe('physical cards: one commitment, printed effects and bounded construction',()=>{
 it('finite cards are nine physical cards; one gesture consumes exactly one card',()=>{const m=start('cards.finite');expect(m.fighters.player.cardZone!.hand).toHaveLength(9);const n=play(m,'rock');expect(n.fighters.player.cardZone!.hand).toHaveLength(8);expect(n.fighters.player.cardZone!.discard).toHaveLength(1);expect(n.history[0].player.cardId).toBeTruthy();expect(m.fighters.player.cardZone!.hand).toHaveLength(9);});
 it('deck starts with nine cards and five in hand without creating life or extra hands',()=>{const m=start('experiment.deck');expect(total(m)).toBe(9);expect(m.fighters.player.cardZone!.hand).toHaveLength(5);expect(m.design.goal).toBe('single');const committed=commitComputer(m),n=resolveAttempt(committed,legalActions(committed,'player')[0]!,'one');expect(n.result?.reason).toBe('single');});
 it('rejects another card identity, mismatched gesture and removed modifier payload atomically',()=>{const m=commitComputer(start('experiment.modifiers'));const a=legalActions(m,'player')[0]!;expect(()=>resolveAttempt(m,{...a,cardId:'missing'},'bad')).toThrow();expect(()=>resolveAttempt(m,{...a,kind:'paper'},'bad2')).toThrow();expect(()=>resolveAttempt(m,{...a,experiment:{modifier:0}},'bad3')).toThrow();expect(m.history).toHaveLength(0);});
 it('bloodstone heals only actual main attack life loss, respecting range and shield',()=>{const m=start('life.knockout','experiment.modifiers');m.fighters.player.life=1;expect(play(m,'bloodstone').fighters.player.life).toBe(2);m.fighters.computer.shield=1;expect(play(m,'bloodstone').fighters.player.life).toBe(1);const r=start('life.knockout','experiment.modifiers','experiment.range');r.experiment!.distance=2;r.fighters.player.life=1;expect(play(r,'bloodstone').fighters.player.life).toBe(1);});
 it('bastion shields before damage and gives up winning damage',()=>{const m=start('life.knockout','experiment.modifiers');expect(play(m,'bastion').fighters.computer.life).toBe(3);expect(play(m,'bastion','paper').fighters.player.life).toBe(3);});
 it('needle breaks a shield and relay requires the previous effective paper',()=>{const m=start('life.knockout','experiment.modifiers');m.fighters.computer.shield=1;expect(play(m,'needle','paper').fighters.computer.life).toBe(2);m.fighters.computer.shield=0;m.fighters.player.lastAction='paper';expect(play(m,'relay','paper').fighters.computer.life).toBe(1);m.fighters.player.lastAction='rock';expect(play(m,'relay','paper').fighters.computer.life).toBe(2);});
 it('echo and draw refund return the same printed card only once',()=>{const m=start('life.knockout','experiment.modifiers','cards.draw_refund');const before=m.fighters.player.cardZone!.hand.find(c=>c.definition==='echo')!;const n=play(m,'echo','paper');expect(n.fighters.player.cardZone!.hand.filter(c=>c.uid===before.uid)).toHaveLength(1);expect(total(n)).toBe(total(m));});
 it('capture copies the actual defeated card and leaves the original in enemy discard',()=>{const m=start('life.knockout','experiment.modifiers','cards.capture');const n=play(m,'bloodstone','needle');expect(n.fighters.player.cardZone!.hand.some(c=>c.definition==='needle')).toBe(true);expect(n.fighters.computer.cardZone!.discard.some(c=>c.definition==='needle')).toBe(true);expect(total(n)).toBe(10);});
 it('refills to five after a hand, retains unplayed identities and never exceeds seven on draw',()=>{let m=start('life.knockout','experiment.deck');give(m,'player','rock','rock','paper','scissors','echo');give(m,'computer','rock','scissors','paper');const retained=m.fighters.player.cardZone!.hand.slice(1).map(c=>c.uid);m=advanceMatch(play(m,'rock','rock'));expect(m.fighters.player.cardZone!.hand).toHaveLength(5);for(const uid of retained)expect(m.fighters.player.cardZone!.hand.some(c=>c.uid===uid)).toBe(true);drawCards(m,'player',20);expect(m.fighters.player.cardZone!.hand).toHaveLength(7);});
 it('a void retry preserves cards, draws, forge currency and once-per-hand opportunities',()=>{let m=start('life.knockout','experiment.modifiers','experiment.bag');m.design=setAbility(m.design,'player','ability.retry');m=createMatch(m.design,2);const before=structuredClone(m.fighters.player.cardZone);const n=play(m,'scissors','rock',true);expect(n.history[0].voided).toBe(true);expect(n.fighters.player.cardZone).toEqual(before);expect(()=>craftCard(n,recipes(n)[0].id)).toThrow();});
 it('forge adds a physical card to discard, spends currency once and cannot reopen at terminal',()=>{let m=start('life.knockout','experiment.deck','experiment.bag');give(m,'player','rock','rock','paper','scissors','echo');give(m,'computer','rock','scissors','paper');m=play(m,'rock','rock');const recipe=recipes(m)[0]!,size=total(m),ink=m.fighters.player.cardZone!.ink;const n=craftCard(m,recipe.id);expect(total(n)).toBe(size+1);expect(n.fighters.player.cardZone!.discard.at(-1)?.definition).toBe(recipe.id);expect(n.fighters.player.cardZone!.ink).toBe(ink-recipe.price);expect(()=>craftCard(n,recipe.id)).toThrow();expect(()=>craftCard({...m,result:{winner:'draw',reason:'single',text:'结束'},phase:'finished'},recipe.id)).toThrow();});
 it('forge thinning has a six-card floor and rejects stale recipe ids',()=>{const m=play(start('life.knockout','cards.finite','experiment.bag'),'rock','rock');expect(()=>craftCard(m,'missing')).toThrow();const id=m.fighters.player.cardZone!.hand[0]!.uid,n=craftCard(m,null,id);expect(total(n)).toBe(total(m)-1);expect(n.fighters.player.cardZone!.hand.some(c=>c.uid===id)).toBe(false);const tiny=structuredClone(m);tiny.fighters.player.cardZone!.hand=tiny.fighters.player.cardZone!.hand.slice(0,5);expect(()=>craftCard(tiny,null,tiny.fighters.player.cardZone!.hand[0]!.uid)).toThrow();});
 it('mulligan consumes its opportunity without changing the sealed CPU action',()=>{const m=commitComputer(start('life.knockout','experiment.deck','experiment.shuffle'));const id=m.fighters.player.cardZone!.hand[0]!.uid;const n=mulliganCard(m,id);expect(n.computerCommitment).toEqual(m.computerCommitment);expect(n.fighters.player.cardZone!.hand).toHaveLength(5);expect(n.fighters.player.cardZone!.discard.some(c=>c.uid===id)).toBe(true);expect(()=>mulliganCard(n,n.fighters.player.cardZone!.hand[0]!.uid)).toThrow();});
 it('CPU observations exclude player physical cards; public views hide opponent zones including history',()=>{const m=start('life.knockout','experiment.modifiers'),n=play(m,'rock');expect(makeObservation(m).opponent.cardZone).toBeUndefined();const changed=structuredClone(m);changed.fighters.player.cards.rock=0;expect(makeObservation(m)).toEqual(makeObservation(changed));const view=projectPublicView(n);expect(view.fighters.computer.cardZone).toBeUndefined();expect(view.history[0].before.computer.cardZone).toBeUndefined();expect(view.history[0].after.computer.cardZone).toBeUndefined();});
 it('all 13 functional card definitions resolve without creating negative resources',()=>{for(const card of CARD_LIBRARY.filter(c=>c.effect!=='plain')){let m=start('life.knockout','experiment.deck','experiment.bag','experiment.push','energy.active_charge');give(m,'player',card.id);give(m,'computer','rock');m=play(m,card.id,'rock');for(const f of Object.values(m.fighters)){expect(f.life).toBeGreaterThanOrEqual(0);expect(f.energy).toBeGreaterThanOrEqual(0);for(const g of compileDesign(m.design).gestures)expect(f.cards[g]).toBe(f.cardZone!.hand.filter(c=>cardDefinition(c.definition).kind===g).length);}}});
 it('removed groups cannot be installed, even through a direct engine call',()=>{for(const key of ['declaration','pledge','prediction','information','queue','script','delayed','speed','stash','risk','loan','insurance','forecast','surprise','well','furnace'])expect(()=>installRule(createDesign(),`experiment.${key}` as RuleId)).toThrow();});
});

it('the computer uses the same forge budget and constructs only between effective hands',()=>{
 let m=start('life.knockout','cards.finite','experiment.bag');m=play(m,'rock','rock');const size=total(m,'computer');m=advanceMatch(m);expect(total(m,'computer')).toBe(size+1);expect(m.fighters.computer.cardZone!.ink).toBeLessThan(3);
});
it('mixed active rules preserve unique physical cards and inventory consistency across seeds',()=>{
 const design=ALL_CHOICES.filter(c=>c.kind==='rule').reduce((d,c)=>installRule(d,(c.ruleId??c.id) as RuleId),createDesign());
 for(let seed=0;seed<20;seed++){let m=createMatch(design,seed);for(let turn=0;turn<8&&!m.result;turn++){m=commitComputer(advanceMatch(m));if(m.result)break;const available=legalActions(m,'player');m=resolveAttempt(m,available[(seed+turn)%available.length]!,`mixed-${turn}`);for(const f of Object.values(m.fighters)){const z=f.cardZone!;const ids=[...z.hand,...z.draw,...z.discard].map(c=>c.uid);expect(new Set(ids).size).toBe(ids.length);for(const g of compileDesign(m.design).gestures)expect(f.cards[g]).toBe(z.hand.filter(c=>cardDefinition(c.definition).kind===g).length);expect(f.energy).toBeGreaterThanOrEqual(0);}}}
});
